apiVersion: v1
kind: Service
metadata:
    name: account
    labels:
        name: account
spec:
    type: LoadBalancer
    ports:
        - port: 80
          targetPort: 8080
          protocol: TCP
    selector:
        app: account